common:
    run_label: "run1"
    log_freq: 512
    mixed_precision: true
    profile_first: false
dataset:
    root_train: "./data"
    root_eval: "./data"
    num_classes: 100
    batch_size: 32
    batch_size_eval: 128
    num_workers: 4
    pin_memory: true
mix:
    mixup_beta: 1.0
    cutmix_beta: 1.0
    prob: 0.0
    switch_prob: 0.5
    mode: "batch"
optimizer:
    learning_rate: 0.00005
    weight_decay: 0.002
scheduler:
    warmup_epoch: 5
    cosine_tmax_epoch: 45
    max_epoch: 50
    min_learning_rate: 0.0000001
criterion:
    label_smoothing: 0.1
model:
    model_type: "swin_transformer"
    model_name: "swin_base_patch4_window7_224_in22k"
    input_resolution: 224
    ema_momentum: 0.995
    device_type: "cuda"
